"""add nutrition targets to patient profile

Revision ID: 2df7957b3534
Revises: d40c33666132
Create Date: 2026-09-09 08:14:39.754557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df7957b3534'
down_revision: Union[str, None] = 'd40c33666132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('daily_carb_limit_g', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('daily_calorie_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'daily_calorie_limit')
    op.drop_column('patient_profiles', 'daily_carb_limit_g')
    # ### end Alembic commands ###
