"""add glucose meal_reference and notes

Revision ID: 5e8a8d615bc5
Revises: b3b997676941
Create Date: 2026-09-08 09:54:54.951746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8a8d615bc5'
down_revision: Union[str, None] = 'b3b997676941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glucose_readings', sa.Column('meal_reference', sa.String(), nullable=True))
    op.add_column('glucose_readings', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glucose_readings', 'notes')
    op.drop_column('glucose_readings', 'meal_reference')
    # ### end Alembic commands ###
