"""add granular reminder toggles

Revision ID: 64357820112a
Revises: 85139a321a27
Create Date: 2026-09-08 12:25:50.272669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64357820112a'
down_revision: Union[str, None] = '85139a321a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('morning_dose_reminder', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('evening_dose_reminder', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('missed_dose_alert', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('fasting_glucose_reminder', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('post_meal_glucose_reminder', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('meal_log_reminder', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('exercise_nudge', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'exercise_nudge')
    op.drop_column('notification_preferences', 'meal_log_reminder')
    op.drop_column('notification_preferences', 'post_meal_glucose_reminder')
    op.drop_column('notification_preferences', 'fasting_glucose_reminder')
    op.drop_column('notification_preferences', 'missed_dose_alert')
    op.drop_column('notification_preferences', 'evening_dose_reminder')
    op.drop_column('notification_preferences', 'morning_dose_reminder')
    # ### end Alembic commands ###
