"""add user profile fields gender phone avatar notification channels

Revision ID: 77026ed43a9a
Revises: 64357820112a
Create Date: 2026-09-08 12:35:24.483141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77026ed43a9a'
down_revision: Union[str, None] = '64357820112a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('push_notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_alerts_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_alerts_enabled')
    op.drop_column('users', 'push_notifications_enabled')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
