"""add medication description drug_class side_effects refill_reminder

Revision ID: 85139a321a27
Revises: 5e8a8d615bc5
Create Date: 2026-09-08 12:15:28.207855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85139a321a27'
down_revision: Union[str, None] = '5e8a8d615bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('description', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('drug_class', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('side_effects', sa.JSON(), nullable=False))
    op.add_column('medications', sa.Column('refill_reminder_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'refill_reminder_enabled')
    op.drop_column('medications', 'side_effects')
    op.drop_column('medications', 'drug_class')
    op.drop_column('medications', 'description')
    # ### end Alembic commands ###
