"""add doctor notes to care plan

Revision ID: 9f3035891ecf
Revises: f4f0ec9a9e3b
Create Date: 2026-09-10 15:07:12.785177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3035891ecf'
down_revision: Union[str, None] = 'f4f0ec9a9e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_plans', sa.Column('doctor_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_plans', 'doctor_notes')
    # ### end Alembic commands ###
