"""initial tables

Revision ID: b3b997676941
Revises: 
Create Date: 2026-09-08 09:47:05.735334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b997676941'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('next_milestone_hint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('cuisine_tag', sa.String(), nullable=True),
    sa.Column('default_meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('role', sa.Enum('PATIENT', 'PHYSICIAN', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('care_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescribed_by_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_activity_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('active_minutes', sa.Integer(), nullable=False),
    sa.Column('steps_goal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type', sa.Enum('WALKING', 'CYCLING', 'SWIMMING', 'STRENGTH', 'YOGA', 'CUSTOM', name='exercisetype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Enum('LIGHT', 'MODERATE', 'VIGOROUS', name='exerciseintensity'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glucose_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('reading_type', sa.Enum('FASTING', 'POST_MEAL', 'RANDOM', 'BEDTIME', name='glucosereadingtype'), nullable=False),
    sa.Column('value_mg_dl', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hba1c_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('value_percent', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescribed_by_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('frequency_label', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('dose_times', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medication_reminders', sa.Boolean(), nullable=True),
    sa.Column('glucose_reminders', sa.Boolean(), nullable=True),
    sa.Column('meal_reminders', sa.Boolean(), nullable=True),
    sa.Column('activity_reminders', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('physician_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('hospital_affiliation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.String(), nullable=True),
    sa.Column('family_history', sa.String(), nullable=True),
    sa.Column('smoking_status', sa.String(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_score_max', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'LIKELY_T2DM', name='risklevel'), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_plan_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('GLUCOSE', 'MEDICATION', 'MEAL', 'ACTIVITY', name='careplantasktype'), nullable=False),
    sa.Column('time_of_day', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='timeofday'), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_log_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_log_id', sa.UUID(), nullable=False),
    sa.Column('food_item_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['meal_log_id'], ['meal_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'TAKEN', 'SKIPPED', name='medicationlogstatus'), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diabetes_status', sa.Enum('NOT_DIAGNOSED', 'PREDIABETES', 'TYPE_2_DM', name='diabetesstatus'), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('physical_activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', name='activitylevel'), nullable=True),
    sa.Column('family_history_diabetes', sa.Enum('YES_PARENT', 'YES_SIBLING', 'NO', 'UNSURE', name='familyhistory'), nullable=True),
    sa.Column('smoking_status', sa.Enum('NON_SMOKER', 'EX_SMOKER', 'CURRENT', name='smokingstatus'), nullable=True),
    sa.Column('alcohol_use', sa.Enum('NONE', 'OCCASIONALLY', 'REGULARLY', name='alcoholuse'), nullable=True),
    sa.Column('dietary_habit', sa.Enum('VEGETARIAN', 'NON_VEGETARIAN', 'VEGAN', name='dietaryhabit'), nullable=True),
    sa.Column('preferred_language', sa.Enum('ENGLISH', 'SINHALA', 'TAMIL', name='preferredlanguage'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('linked_physician_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['linked_physician_id'], ['physician_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('care_plan_task_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['care_plan_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('care_plan_task_logs')
    op.drop_table('patient_profiles')
    op.drop_table('medication_logs')
    op.drop_table('meal_plan_entries')
    op.drop_table('meal_log_items')
    op.drop_table('care_plan_tasks')
    op.drop_table('user_achievements')
    op.drop_table('risk_assessments')
    op.drop_table('physician_profiles')
    op.drop_table('notification_preferences')
    op.drop_table('medications')
    op.drop_table('meal_plans')
    op.drop_table('meal_logs')
    op.drop_table('hba1c_results')
    op.drop_table('glucose_readings')
    op.drop_table('exercise_logs')
    op.drop_table('daily_activity_summaries')
    op.drop_table('care_plans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('food_items')
    op.drop_table('achievements')
    # ### end Alembic commands ###
