"""add recipe detail fields to food items

Revision ID: cfc45ee7672b
Revises: 2df7957b3534
Create Date: 2026-09-09 08:23:02.898800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc45ee7672b'
down_revision: Union[str, None] = '2df7957b3534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('description', sa.String(), nullable=True))
    op.add_column('food_items', sa.Column('image_emoji', sa.String(), nullable=True))
    op.add_column('food_items', sa.Column('prep_time_minutes', sa.Integer(), nullable=True))
    op.add_column('food_items', sa.Column('ingredients', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'ingredients')
    op.drop_column('food_items', 'prep_time_minutes')
    op.drop_column('food_items', 'image_emoji')
    op.drop_column('food_items', 'description')
    # ### end Alembic commands ###
