"""add prescription targets to patient profile

Revision ID: f4f0ec9a9e3b
Revises: cfc45ee7672b
Create Date: 2026-09-10 10:20:31.489220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f0ec9a9e3b'
down_revision: Union[str, None] = 'cfc45ee7672b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('fasting_glucose_target', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('post_meal_glucose_target', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('hba1c_target', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('dietary_restrictions', sa.JSON(), nullable=False))
    op.add_column('patient_profiles', sa.Column('exercise_minutes_per_week_target', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('recommended_exercise_types', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'recommended_exercise_types')
    op.drop_column('patient_profiles', 'exercise_minutes_per_week_target')
    op.drop_column('patient_profiles', 'dietary_restrictions')
    op.drop_column('patient_profiles', 'hba1c_target')
    op.drop_column('patient_profiles', 'post_meal_glucose_target')
    op.drop_column('patient_profiles', 'fasting_glucose_target')
    # ### end Alembic commands ###
